name: Inject GA Script

on:
  workflow_call:

jobs:
  inject-ga:
    if: github.repository_owner == 'damzaky'
    runs-on: ubuntu-latest
    env:
      GA_TRACKING_ID: "G-MHQZ4X0HZQ"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Inject GA script and homepage logo
      run: |
        echo "Injecting GA script and homepage logo..."

        GA_SNIPPET="<script async src=\"https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}\"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag(\"js\", new Date());
          gtag(\"config\", \"${GA_TRACKING_ID}\");
        </script>"

        LOGO_SNIPPET='<a id="homepage-logo" href="https://damzaky.github.io/">Damzaky</a>'

        for file in $(find . -name "*.html"); do
          echo "Processing $file..."

          HAS_GA=$(grep -q "${GA_TRACKING_ID}" "$file" && echo yes || echo no)
          HAS_LOGO=$(grep -q 'id="homepage-logo"' "$file" && echo yes || echo no)

          awk -v has_ga="$HAS_GA" -v has_logo="$HAS_LOGO" \
              -v ga="$GA_SNIPPET" -v logo="$LOGO_SNIPPET" '
            {
              # Inject GA snippet before </head> if not present
              if (!injected_ga && has_ga == "no" && /<\/head>/) {
                print ga;
                injected_ga = 1;
              }

              # Inject logo after <body> if not present
              if (!injected_logo && has_logo == "no" && /<body[^>]*>/) {
                print;
                print logo;
                injected_logo = 1;
                next;
              }

              print
            }
          ' "$file" > "$file.injected" && mv "$file.injected" "$file"
        done

    - name: Confirm GA injection
      run: grep "${GA_TRACKING_ID}" index.html || echo "Not injected"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ 
