name: Inject GA Script

on:
  workflow_call:

jobs:
  inject-ga:
    if: github.repository_owner == 'damzaky'  # prevent forked repos from triggering
    runs-on: ubuntu-latest
    env:
      GA_TRACKING_ID: "G-MHQZ4X0HZQ"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Inject debug marker
      run: |
        GA_TRACKING_ID="G-MHQZ4X0HZQ"
        GA_SNIPPET="<script async src=\"https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}\"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag(\"js\", new Date());
          gtag(\"config\", \"${GA_TRACKING_ID}\");
        </script>"

        echo "Injecting debug marker..."
        for file in $(find . -name "*.html"); do
          echo "$GA_SNIPPET" >> "$file"
        done

    - name: Inject GA script
      run: |
        echo "Injecting GA script..."
    
        GA_SNIPPET='<script async src="https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag("js", new Date());
          gtag("config", "${GA_TRACKING_ID}");
        </script>'
    
        for file in $(find . -name "*.html"); do
          if ! grep -q "${GA_TRACKING_ID}" "$file"; then
            awk -v snippet="$GA_SNIPPET" '
              /<head>/ {
                print;
                print snippet;
                next
              }
              { print }
            ' "$file" > "$file.injected"
            mv "$file.injected" "$file"
          fi
        done



    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ 
