name: Inject GA Script

on:
  workflow_call:

jobs:
  inject-ga:
    if: github.repository_owner == 'damzaky'  # prevent forked repos from triggering
    runs-on: ubuntu-latest
    environment: production
    env:
      GA_TRACKING_ID: ${{ vars.GA_TRACKING_ID }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Inject GA script after <head>
      run: |
        echo "Injecting GA script..."
    
        for file in $(find . -name "*.html"); do
          if ! grep -q "${GA_TRACKING_ID}" "$file"; then
            tmpfile=$(mktemp)
            while IFS= read -r line; do
              echo "$line" >> "$tmpfile"
              if echo "$line" | grep -q "<head>"; then
                cat <<EOF >> "$tmpfile"
                <script async src="https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}"></script>
                <script>
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){dataLayer.push(arguments);}
                  gtag("js", new Date());
                  gtag("config", "${GA_TRACKING_ID}");
                </script>
                EOF
              fi
            done < "$file"
            mv "$tmpfile" "$file"
          fi
        done

    - name: Confirm GA injection
      run: grep "${GA_TRACKING_ID}" index.html || echo "Not injected"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ 
