name: Inject GA Script

on:
  workflow_call:

jobs:
  inject-ga:
    if: github.repository_owner == 'damzaky'  # prevent forked repos from triggering
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Inject GA script after <head>
      run: |
        echo "Injecting GA script..."

        GA_TRACKING_ID=${{ vars.GA_TRACKING_ID }}
    
        for file in $(find . -name "*.html"); do
          if ! grep -q "${GA_TRACKING_ID}" "$file"; then
            tmpfile=$(mktemp)
            while IFS= read -r line; do
              echo "$line" >> "$tmpfile"
              if echo "$line" | grep -q "<head>"; then
                echo '<script async src="https://www.googletagmanager.com/gtag/js?id='"${GA_TRACKING_ID}"'"></script>' >> "$tmpfile"
                echo '<script>' >> "$tmpfile"
                echo '  window.dataLayer = window.dataLayer || [];' >> "$tmpfile"
                echo '  function gtag(){dataLayer.push(arguments);}' >> "$tmpfile"
                echo '  gtag("js", new Date());' >> "$tmpfile"
                echo '  gtag("config", "'"${GA_TRACKING_ID}"'");' >> "$tmpfile"
                echo '</script>' >> "$tmpfile"
              fi
            done < "$file"
            mv "$tmpfile" "$file"
          fi
        done

    - name: Confirm GA injection
      run: grep "${GA_TRACKING_ID}" index.html || echo "Not injected"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ 
