name: Inject GA Script

on:
  workflow_call:

jobs:
  inject-ga:
    if: github.repository_owner == 'damzaky'  # prevent forked repos from triggering
    runs-on: ubuntu-latest
    environment: production
    env:
      GA_TRACKING_ID: ${{ vars.GA_TRACKING_ID }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Inject GA script
      run: |
        echo "Injecting GA script..."
    
        GA_SNIPPET=$(cat <<EOF
        <script async src="https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag("js", new Date());
          gtag("config", "${GA_TRACKING_ID}");
        </script>
        EOF
        )
    
        for file in $(find . -name "*.html"); do
          if ! grep -q "${GA_TRACKING_ID}" "$file"; then
            awk -v snippet="$GA_SNIPPET" '
              /<head[^>]*>/ {
                print;
                print snippet;
                next
              }
              { print }
            ' "$file" > "$file.injected"
            mv "$file.injected" "$file"
          fi
        done


    - name: Confirm GA injection
      run: grep "${GA_TRACKING_ID}" index.html || echo "Not injected"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ 
