name: Inject GA Script

on:
  workflow_call:

jobs:
  inject-ga:
    if: github.repository_owner == 'damzaky'  # prevent forked repos from triggering
    runs-on: ubuntu-latest
    env:
      GA_TRACKING_ID: ${{ vars.GA_TRACKING_ID }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Inject debug marker
      run: |
        echo "Injecting debug marker..."
        for file in $(find . -name "*.html"); do
          echo "<!-- DEBUG_MARKER -->" >> "$file"
        done

    - name: Confirm GA injection
      run: grep "${GA_TRACKING_ID}" index.html || echo "Not injected"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ 
